finos/rune-dsl

com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/RosettaGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/FunctionGenerator.xtend
... so that implementations can actually override them
=> Make constructor and abstract method protected

com.regnosys.rosetta/src/com/regnosys/rosetta/generator/RosettaGenerator.xtend
Remove a couple of places where sysout was used instead of logging
=> replace sysout with proper logging

com.regnosys.rosetta.lib/src/main/java/com/rosetta/model/lib/records/Date.java, com.regnosys.rosetta.lib/src/main/java/com/rosetta/model/lib/records/DateImpl.java, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/calculation/RosettaCalculationGenerationTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/calculation/RosettaFunctionGenerationTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/object/RosettaObjectGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/tests/RosettaExpressionsTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/tests/util/ModelHelper.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/CalculationGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/RosettaToJavaExtensions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/FunctionGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/JavaQualifiedTypeProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/RosettaExpressionJavaGeneratorForFunctions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/object/MetaFieldGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/util/JavaClassTranslator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/types/RosettaTypeProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/types/RosettaTypes.xtend
external function migration + Guice injection
=> Grammar refactoring

com.regnosys.rosetta/src/com/regnosys/rosetta/generator/RosettaGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/CalculationGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/JavaNames.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/RosettaExternalFunctionDependencyProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/RosettaToJavaExtensions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/FunctionGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/RosettaExpressionJavaGeneratorForFunctions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/util/RosettaFunctionExtensions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/types/RosettaTypeProvider.xtend
Enum calculation is now supported
=> Expand 'func' features to fully support 'calculation' #20

com.regnosys.rosetta.lib/.classpath, com.regnosys.rosetta/model/RosettaSimple.xcore, com.regnosys.rosetta/src/com/regnosys/rosetta/Rosetta.xtext, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/CalculationGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/RosettaExternalFunctionDependencyProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/calculation/RosettaToJavaExtensions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/RosettaExpressionJavaGeneratorForFunctions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/util/JavaNames.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/util/RosettaFunctionExtensions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/scoping/RosettaScopeProvider.xtend
Support multi assign-output for paths #28
=> Assign output

com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/object/MetaFieldGenerator.xtend
=> Add equals and hashcode methods to MetaFieldsBuilder and

com.regnosys.rosetta.ide/src/com/regnosys/rosetta/ide/highlight/RosettaHighlightingCalculator.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend, com.regnosys.rosetta.ui.tests/src/com/regnosys/rosetta/ui/tests/contentassist/AbstractContentAssistTest.xtend, com.regnosys.rosetta.ui.tests/src/com/regnosys/rosetta/ui/tests/contentassist/RosettaContentAssistTest.xtend, com.regnosys.rosetta.ui/src/com/regnosys/rosetta/ui/contentassist/RosettaProposalProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/GenerateRosetta.mwe2, com.regnosys.rosetta/src/com/regnosys/rosetta/Rosetta.xtext, com.regnosys.rosetta/src/com/regnosys/rosetta/validation/RosettaValidator.xtend
This PR also handles `type` keyword conflict with existing model `RosettaNamed` elements.
=> Enumeration ca

com.regnosys.rosetta.ide/src/com/regnosys/rosetta/ide/highlight/RosettaHighlightingCalculator.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/object/SynonymGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/tests/RosettaParsingTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend, com.regnosys.rosetta.ui.tests/src/com/regnosys/rosetta/ui/tests/validation/RosettaUIValidationTest.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/validation/RosettaValidator.xtend
=> Validate path syntax 117

com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/rule/ChoiceRuleGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/rule/DataRuleGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/tests/util/DataRuleHelper.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/RosettaExtensions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/rule/ChoiceRuleGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/rule/DataRuleGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/scoping/RosettaScopeProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/validation/RosettaValidator.xtend
New condition name pattern #107 
Validator vor choice #46
=> Conditions 107

com.regnosys.rosetta.lib/src/main/java/com/rosetta/model/lib/RosettaKeyValue.java, com.regnosys.rosetta.lib/src/main/java/com/rosetta/model/lib/RosettaKeyValueBuilder.java, com.regnosys.rosetta.lib/src/main/java/model/annotations.rosetta, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/object/ExternalHashcodeGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/object/RosettaKeyGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/object/RosettaObjectGeneratorTest.xtend, com.regnosys.rosetta/model/Rosetta.xcore, com.regnosys.rosetta/src/com/regnosys/rosetta/Rosetta.xtext, com.regnosys.rosetta/src/com/regnosys/rosetta/RosettaExtensions.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/object/MetaFieldGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/object/ModelObjectBoilerPlate.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/object/ModelObjectGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/object/ExpandedAttribute.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/util/RosettaAttributeExtensions.xtend, com.regnosys.rosetta/text/description.txt
Rename rosettaKey to globalKey for consistency
=> Remove partial key annotation and remove related code

com.regnosys.rosetta.lib/src/main/java/com/rosetta/model/lib/GlobalKeyBuilder.java
Reverts REGnosys/rosetta-dsl#187
=> Revert "Override"

com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/object/RosettaEnumGeneratorTest.xtend, com.regnosys.rosetta/model/Rosetta.xcore, com.regnosys.rosetta/src/com/regnosys/rosetta/Rosetta.xtext
added changes for allowing 'workflow' keyword in the namespace and adding support for annotations for enum
=> allow annotations for enum

README.rst
=> README makes clear that CDM repo is private

com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/calculation/FuncGeneratorTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/generator/java/expression/ListOperationTest.xtend, com.regnosys.rosetta.tests/src/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend, com.regnosys.rosetta/model/Rosetta.xcore, com.regnosys.rosetta/model/RosettaSimple.xcore, com.regnosys.rosetta/src/com/regnosys/rosetta/Rosetta.xtext, com.regnosys.rosetta/src/com/regnosys/rosetta/formatting2/RosettaFormatter.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/CardinalityProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/generator/java/function/FuncGenerator.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/types/RosettaTypeProvider.xtend, com.regnosys.rosetta/src/com/regnosys/rosetta/validation/RosettaValidator.xtend
=> [dsl] Replace distinct and only-element with list operations #325 #326

com.regnosys.rosetta.blueprint-lib/pom.xml, com.regnosys.rosetta.ide/pom.xml, com.regnosys.rosetta.lib/pom.xml, com.regnosys.rosetta.target/pom.xml, com.regnosys.rosetta.tests/pom.xml, com.regnosys.rosetta.ui.tests/pom.xml, com.regnosys.rosetta.ui/pom.xml, com.regnosys.rosetta/pom.xml
See issue https://github.com/renovatebot/renovate/issues/18619
=> Renovate setup fix

rosetta-runtime/src/main/java/com/rosetta/model/lib/expression/ExpressionEqualityUtil.java
=> task-3062: make error message more relevant

rosetta-lang/src/main/java/com/regnosys/rosetta/formatting2/RosettaFormatter.xtend, rosetta-tools/src/test/resources/model-import/data-and-enum-result/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/data-result/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/data2-result/ns-type.rosetta
Update typeAlias formatting so each declaration is separated by a new line
=> Update typeAlias formatting

documentation/rosetta-modelling-component.md
Update documentation for parameterized type and type aliases
- Documentation
=> Update documentation for parameterized type and type aliases

documentation/rosetta-modelling-component.md, pom.xml, rosetta-lang/pom.xml, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/RosettaGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ModelMetaGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ModelObjectGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ValidatorsGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/util/BackwardCompatibilityGenerator.xtend, rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/AbstractRosettaGeneratorMojo.java, rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/RosettaGenerateMojo.java, rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/RosettaTestGenerateMojo.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/expression/ExpressionOperators.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/meta/BasicRosettaMetaData.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/meta/Key.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/meta/RosettaMetaData.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/validation/ValidationResult.java, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/util/CodeGeneratorTestHelper.xtend, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/util/ModelHelper.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/expression/ExpressionGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ModelMetaGeneratorTest.xtend, rosetta-tools/src/test/java/com/regnosys/rosetta/tools/modelimport/XsdImportTest.java
This changes adds the generation of a new validator for validating the type format of attributes.
=> Runtime type format validation 

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ValidatorsGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/util/BackwardCompatibilityGenerator.xtend, rosetta-runtime/src/main/java/com/rosetta/model/lib/meta/Key.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/validation/ValidationResult.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ModelMetaGeneratorTest.xtend
Patch for backwards compatibility.
=> Revert `ValidationTypeEnum` to remain backwards compatible

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ValidatorsGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/util/BackwardCompatibilityGenerator.xtend, rosetta-runtime/src/main/java/com/rosetta/model/lib/meta/Key.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/meta/RosettaMetaData.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/validation/ValidationResult.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ModelMetaGeneratorTest.xtend
Makes type format validation backwards compatible.
=> Type format validation patch

README.md
=> task-3149: Update dead link

pom.xml, rosetta-ide/pom.xml, rosetta-ide/src/main/java/com/regnosys/rosetta/ide/util/AbstractLanguageServerService.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/RosettaGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/blueprints/BlueprintGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/scoping/RosettaScopeProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/RosettaSimpleValidator.xtend, rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/RosettaStandaloneBuilder.java, rosetta-runtime-blueprints/pom.xml, rosetta-runtime-blueprints/src/main/java/com/regnosys/rosetta/blueprints/DataItemReportUtils.java, rosetta-runtime-blueprints/src/main/java/com/regnosys/rosetta/blueprints/runner/StreamProcessor.java, rosetta-runtime-blueprints/src/main/java/com/regnosys/rosetta/blueprints/runner/nodes/ProcessorNode.java
Remove reload4j references in code and replace with slf4j
=> Remove reload4j references in code and replace with slf4j

rosetta-lang/src/main/java/com/regnosys/rosetta/validation/RosettaSimpleValidator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend
=> Patch for misidentifying mandatory then's

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/function/FunctionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/rule/DataRuleGenerator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/rule/ChoiceRuleGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/rule/ConditionTestHelper.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/rule/DataRuleGeneratorTest.xtend
STORY-2485 - Java code-gen - add interface and default implementation for validators to allow implementors to override conditions (required for DRR external API)
=> STORY-2485 Java code-gen - add interface and default implementation for validators

rosetta-ide/src/main/java/com/regnosys/rosetta/ide/semantictokens/RosettaSemanticTokensService.java, rosetta-lang/model/Rosetta.xcore, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/JavaIdentifierRepresentationService.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/RuleInstanceRepresentation.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/blueprints/BlueprintGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java, rosetta-lang/src/main/java/com/regnosys/rosetta/scoping/RosettaScopeProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/types/CardinalityProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/types/Rosetta.xsemantics, rosetta-lang/src/main/java/com/regnosys/rosetta/types/RosettaTypeChecking.xsemantics, rosetta-lang/src/main/java/com/regnosys/rosetta/types/RosettaTypeProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/RosettaSimpleValidator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/blueprints/RosettaBlueprintTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/rule/RosettaRuleGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend, rosetta-xcore-plugin-dependencies/pom.xml
Making it possible to call rules as part of the expression syntax harmonisation.
=> Harmonisation rule calls

documentation/rosetta-modelling-component.md
=> Update docs with latest demo snippets

rosetta-runtime/src/main/java/com/rosetta/model/lib/ModelConfig.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/ModuleConfig.java
=> ModuleConfig annotation to help programmatically find runtime modules

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ValidatorsGenerator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ModelMetaGeneratorTest.xtend
=> Stale validator

documentation/rosetta-modelling-component.md, rosetta-lang/src/main/java/com/regnosys/rosetta/RosettaExtensions.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ValidatorsGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/types/TypeSystem.java, rosetta-lang/src/main/java/com/regnosys/rosetta/utils/ExternalAnnotationUtil.java, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/RosettaSimpleValidator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/StandaloneRosettaTypingValidator.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ModelMetaGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend
=> Validation on input types for rules with overriden attributes patch

rosetta-lang/src/main/java/com/regnosys/rosetta/formatting2/RosettaExpressionFormatter.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/scoping/RosettaScopeProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/types/CardinalityProvider.xtend, rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperUtils.java, rosetta-testing/src/test/java/com/regnosys/rosetta/formatting2/RosettaExpressionFormattingTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/formatting2/RosettaFormattingTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/condition/DataRuleGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/expression/ListOperationTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend
=> Validation, code generation and formatting patches

rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperUtils.java
=> Backwards compat patch

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperC.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperListOfLists.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperS.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperUtils.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/expression/ListOperationTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/rule/RosettaRuleGeneratorTest.xtend
=> Backwards compatibility patch

rosetta-lang/src/main/java/com/regnosys/rosetta/derivedstate/RosettaDerivedStateComputer.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend
Bug fix for code generation error for `then join`.
=> Fixed `then join` bug

rosetta-lang/src/main/java/com/regnosys/rosetta/types/RObjectFactory.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/blueprints/RosettaBlueprintTest.xtend
=> handle report naming for legacy and non legacy reports

rosetta-lang/src/main/java/com/regnosys/rosetta/Rosetta.xtext, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/types/CardinalityProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/RosettaSimpleValidator.xtend
=> Constructor patch

documentation/rosetta-modelling-component.md
=> Docs update

rosetta-runtime/src/main/java/com/rosetta/model/lib/expression/ComparisonResult.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperUtils.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend
Implement fix for https://github.com/REGnosys/rosetta-dsl/issues/673
=> Handle empty comparison results 

documentation/rosetta-modelling-component.md
Update description in documentation of list comparisons
=> Fix list comparison docs

rosetta-lang/model/Rosetta.xcore, rosetta-lang/src/main/java/com/regnosys/rosetta/Rosetta.xtext, rosetta-lang/src/main/java/com/regnosys/rosetta/formatting2/RosettaFormatter.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/StandaloneRosettaTypingValidator.java, rosetta-maven-plugin/.classpath
=> Added eligibility to ecore

documentation/rosetta-modelling-component.md
=> Add keyword clash section to the docs

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/util/RecordJavaUtil.xtend, rosetta-runtime/src/main/java/com/rosetta/model/lib/expression/MapperMaths.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend
=> Null fixes

docs/rune-modelling-component.md
Fixed issue https://github.com/finos/rune-dsl/issues/522
- This change is a documentation update
=> Update list comparison docs

.github/workflows/release.yml
=> Revert "chore(deps): update actions/setup-java action to v4"

pom.xml, rosetta-lang/pom.xml, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/util/ExpressionParser.xtend
=> Fixed issue with infinite compile

rosetta-lang/src/main/java/com/regnosys/rosetta/Rosetta.xtext
=> Add definition to ChoiceOption

rosetta-lang/model/RosettaSimple.xcore, rosetta-testing/src/test/java/com/regnosys/rosetta/tests/RosettaParsingTest.xtend
=> Fixed scoping bug

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-runtime/src/main/java/com/rosetta/model/lib/expression/ExpressionOperators.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend
=> Fix null pointers for `only exists`

rosetta-lang/model/RosettaSimple.xcore, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/GeneratorScope.java
=> Fixed infinite choice option generation

rosetta-runtime/src/main/java/com/rosetta/model/lib/expression/ExpressionOperators.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend
=> Fix only exists list handling

.gitignore, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/DeepPathUtilGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/scoping/RosettaScopeProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/utils/DeepFeatureCallUtil.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend
=> Fixed metadata on deep path operator

rosetta-lang/src/main/java/com/regnosys/rosetta/Rosetta.xtext, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend
=> Fixed metadata on choice options

rosetta-lang/src/main/java/com/regnosys/rosetta/config/RosettaConfiguration.java, rosetta-lang/src/main/java/com/regnosys/rosetta/config/RosettaGeneratorsConfiguration.java, rosetta-lang/src/main/java/com/regnosys/rosetta/config/RosettaModelConfiguration.java, rosetta-lang/src/main/java/com/regnosys/rosetta/config/RosettaTabulatorConfiguration.java, rosetta-lang/src/main/java/com/regnosys/rosetta/config/file/FileBasedRosettaConfigurationProvider.java, rosetta-lang/src/main/java/com/regnosys/rosetta/config/file/NamespaceFilter.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/reports/TabulatorGenerator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/config/RosettaConfigurationTest.java, rosetta-testing/src/test/resources/rosetta-config-test-without-tabulators.yml
=> Fix null pointers in rosetta config

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/reports/TabulatorGenerator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ConfigurableTypeTabulatorTest.xtend, rosetta-testing/src/test/resources/rosetta-tabulator-type-config-model2.yml
Fix tabulation bug - missing close bracket
=> story 959 task-5023: fix tabulation bug - missing close bracket

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/reports/TabulatorGenerator.xtend, rosetta-runtime/src/main/java/com/rosetta/model/lib/reports/Tabulator.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ConfigurableTypeTabulatorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/reports/TabulatorTest.xtend
=> Fix tabulator performance

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/function/FunctionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/ConfigurableTypeTabulatorTest.xtend
=> Fix for meta generation

rosetta-lang/src/main/java/com/regnosys/rosetta/types/RAttribute.java, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/reports/ReportingTest.xtend
=> Fix report generator

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ModelObjectBoilerPlate.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/PojoRegressionTest.xtend
=> Fix Pojo process method to include meta attributes

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ModelObjectBoilerPlate.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/object/PojoRegressionTest.xtend
=> Process meta fix

rosetta-lang/src/main/java/com/regnosys/rosetta/GenerateRosetta.mwe2, rosetta-xcore-plugin-dependencies/.project, rosetta-xcore-plugin-dependencies/pom.xml, rosetta-xcore-plugin-dependencies/src/main/java/com/regnosys/rosetta/xcore/generator/serializer/RosettaSerializerFragment.xtend
This fix addresses issue #825 which causes and invalid semantic sequencer to be generated
=> Fix semantic sequencer generation

rosetta-lang/src/main/java/com/regnosys/rosetta/cache/RequestScopedCache.java
=> Disabled cache

rosetta-tools/src/main/java/com/regnosys/rosetta/tools/modelimport/XsdUtil.java, rosetta-tools/src/test/resources/model-import/data-and-enum/expected/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/data-and-enum/schema.xsd
=> Xsd import to handle type names with underscore

rosetta-ide/rosetta.tmLanguage.yaml, rosetta-ide/src/main/java/com/regnosys/rosetta/ide/textmate/GenerateTmGrammar.java
=> Fixed highlighting for monaco

rosetta-runtime/src/main/java/com/rosetta/model/lib/functions/IsLeapYear.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/functions/Max.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/functions/Min.java
=> Handle null for Min Max and IsLeapYear

rosetta-runtime/src/main/java/com/rosetta/model/lib/functions/IsLeapYear.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/functions/Max.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/functions/Min.java
=> Null fix for Min and Max

rosetta-runtime/src/main/java/com/rosetta/util/serialisation/TypeXMLConfiguration.java, rosetta-tools/src/main/java/com/regnosys/rosetta/tools/modelimport/ImportTargetConfig.java, rosetta-tools/src/test/java/com/regnosys/rosetta/tools/modelimport/ImportConfigTest.java
=> Fixed null in config

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/reports/TabulatorGenerator.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorHelper.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/rule/RosettaRuleGeneratorTest.xtend
=> Nested type tabulator fix

docs/rune-modelling-component.md
=> Update docs on attribute overrides

checkstyle.xml
=> Windows fix for checkstyle.xml

rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/RosettaStandaloneBuilder.java
=> Workaround for switch issue

rosetta-lang/src/main/java/com/regnosys/rosetta/resource/RosettaResourceDescriptionStrategy.java
See issue https://github.com/finos/rune-dsl/issues/897
=> Fatal error occurs when reporting rule is not given a name

rosetta-lang/src/main/java/com/regnosys/rosetta/generator/util/RosettaFunctionExtensions.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/RosettaSimpleValidator.xtend, rosetta-runtime/src/main/resources/model/annotations.rosetta, rosetta-testing/src/test/java/com/regnosys/rosetta/generator/java/reports/TabulatorTest.xtend, rosetta-testing/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend
=> add new transform annotations

rosetta-ide/src/main/java/com/regnosys/rosetta/ide/quickfix/RosettaQuickFixProvider.java, rosetta-ide/src/test/java/com/regnosys/rosetta/ide/quickfix/QuickFixTest.xtend, rosetta-integration-tests/src/test/java/com/regnosys/rosetta/types/RosettaTypeProviderTest.xtend, rosetta-integration-tests/src/test/java/com/regnosys/rosetta/validation/ExpressionValidatorTest.java, rosetta-integration-tests/src/test/java/com/regnosys/rosetta/validation/RosettaValidatorTest.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/utils/ConstructorManagementService.java, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/RosettaSimpleValidator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/expression/AbstractExpressionValidator.java, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/expression/ConstructorValidator.java, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/expression/ExpressionValidator.java, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/testmodel/RosettaTestModel.java, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/testmodel/RosettaTestModelService.java, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/util/ExpressionParser.xtend
=> Constructor fix

docs/rune-java-documentation.md, rosetta-integration-tests/.project, rosetta-integration-tests/src/test/java/com/regnosys/rosetta/tests/NoEcoreValidatorTest.java, rosetta-lang/src/main/java/com/regnosys/rosetta/RosettaStandaloneSetup.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/util/RosettaFunctionExtensions.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/types/RosettaTypeProvider.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/AbstractDeclarativeRosettaValidator.java, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/RosettaInjectorProvider.java
=> Fixed validation propagated errors

rosetta-integration-tests/pom.xml, rosetta-testing/pom.xml
=> Remove Java 17 on tests project

docs/rune-java-documentation.md, docs/rune-modelling-component.md
=> Label annotation documentation

rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/function/LabelProviderGeneratorTest.java, rosetta-integration-tests/src/test/resources/label-annotations/func-circular/MyFuncLabelProvider.java, rosetta-integration-tests/src/test/resources/label-annotations/func-ingest/MyFuncLabelProvider.java, rosetta-integration-tests/src/test/resources/label-annotations/report-with-complex-labels/BodyCorpusLabelProvider.java, rosetta-integration-tests/src/test/resources/label-annotations/report-with-rule-references/BodyCorpusLabelProvider.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/function/LabelProviderGenerator.xtend, rosetta-runtime/src/main/java/com/regnosys/rosetta/lib/labelprovider/GraphBasedLabelProvider.java, rosetta-runtime/src/main/java/com/regnosys/rosetta/lib/labelprovider/LabelNode.java
=> Support for labels on circular types

rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/function/LabelProviderGeneratorTest.java, rosetta-integration-tests/src/test/resources/label-annotations/report-with-external-source/BodyCorpusLabelProvider.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/function/LabelProviderGenerator.xtend
=> Rule source label fix

rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/reports/ReportGeneratorTest.java, rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/reports/TabulatorTest.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/utils/ExternalAnnotationUtil.java
=> Fix extended rule source with extended type

checkstyle.xml, rosetta-integration-tests/checkstyle-for-deprecated-guice.xml
=> Forbid javax.inject

rosetta-runtime/src/main/java/com/rosetta/model/lib/validation/Validator.java
=> Patch validator interface

rosetta-ide/rosetta.tmLanguage.yaml
=> Fixed highlighting

rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/AbstractRosettaGeneratorMojo.java, rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/RosettaStandaloneBuilder.java
=> Workaround for ordering issue

rosetta-integration-tests/src/test/java/com/regnosys/rosetta/validation/ExpressionValidatorTest.java, rosetta-lang/src/main/java/com/regnosys/rosetta/validation/expression/ExpressionValidator.java, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/validation/RosettaValidationTestHelper.java
=> Disallowed enum type references in expressions

rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/expression/SortOperationTest.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/mapper/MapperC.java, rosetta-testing/src/main/java/com/regnosys/rosetta/tests/testmodel/JavaTestModel.java
=> Make sort, max and min operations null-safe

rosetta-lang/pom.xml, rosetta-maven-plugin/src/main/java/com/regnosys/rosetta/maven/ResourceFormatterMojo.java
=> Fix null pointer in formatting plugin

rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/condition/TypeAliasConditionTest.java, rosetta-runtime/src/main/java/com/rosetta/model/lib/validation/Validator.java
=> Patch Validator class for backwards compatibility

pom.xml
=> Add gpg keys for maven-gpg-plugin

rosetta-tools/src/main/java/com/regnosys/rosetta/tools/modelimport/XsdImport.java, rosetta-tools/src/main/java/com/regnosys/rosetta/tools/modelimport/XsdTypeImport.java, rosetta-tools/src/test/java/com/regnosys/rosetta/tools/modelimport/XsdImportTest.java, rosetta-tools/src/test/resources/model-import/inline-complexContent/expected/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/inline-complexContent/expected/xml-config.json, rosetta-tools/src/test/resources/model-import/inline-complexContent/schema.xsd, rosetta-tools/src/test/resources/model-import/inline-group/expected/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/inline-group/expected/xml-config.json, rosetta-tools/src/test/resources/model-import/inline-group/schema.xsd, rosetta-tools/src/test/resources/model-import/inline-nested-group/expected/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/inline-nested-group/expected/xml-config.json, rosetta-tools/src/test/resources/model-import/inline-nested-group/schema.xsd, rosetta-tools/src/test/resources/model-import/inline-sequence/expected/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/inline-sequence/expected/xml-config.json, rosetta-tools/src/test/resources/model-import/inline-sequence/schema.xsd, rosetta-tools/src/test/resources/model-import/inline/expected/ns-type.rosetta, rosetta-tools/src/test/resources/model-import/inline/expected/xml-config.json, rosetta-tools/src/test/resources/model-import/inline/schema.xsd, rosetta-tools/src/test/resources/model-import/multi/expected/confirmation-type.rosetta
=> Add support for the import of XSD inline types

.github/workflows/release.yml, pom.xml
=> Fix GPG signing

.github/workflows/release.yml, pom.xml
=> Revert FINOS parent upgrade

README.md, rosetta-runtime/src/main/resources/model/annotations.rosetta
=> Test patch

.github/workflows/branch-deploy.yml
=> Updates to the branch deploy wait step

rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/function/FunctionGeneratorMetaTest.java, rosetta-integration-tests/src/test/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslatorTest.java, rosetta-lang/src/main/java/com/regnosys/rosetta/RosettaEcoreUtil.java, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/expression/ExpressionGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/object/ModelObjectGenerator.xtend, rosetta-lang/src/main/java/com/regnosys/rosetta/generator/java/types/JavaTypeTranslator.java, rosetta-lang/src/main/java/com/regnosys/rosetta/types/RMetaAnnotatedType.java, rosetta-lang/src/main/java/com/regnosys/rosetta/utils/PojoPropertyUtil.java
=> Fix metadata template Java type

.github/workflows/cve-scanning.yml, rosetta-ide/vscode/package-lock.json, rosetta-ide/vscode/package.json
=> Update CVE scanning workflow to run faster and fix CVE issue

.github/workflows/branch-deploy.yml, .github/workflows/main-build.yml, .github/workflows/release.yml, pom.xml
=> Add wait to workflows for release availability polling

.github/workflows/release.yml
=> Enable Maven debug mode in release workflow

.github/workflows/release.yml, pom.xml, rune-ide/pom.xml
=> Remove unused `addjars-maven-plugin` from project

rosetta-backport/pom.xml, rosetta-backport/rosetta-lang/pom.xml
=> Add rosetta-lang module to backport
